theme: minima
title: SkiScope
baseurl: "/SkiScope"

navbar:
  - title: Home
    url: /

  - title: Features
    url: /features.html
    children:
      - title: Suche
        url: /01_search.html
      - title: Skigebiet Informationen
        url: /02_skigebiet_informationen.html
      - title: Wetterdaten
        url: /03_wetterdaten.html
      - title: Layersteuerung
        url: /04_layersteuerung.html
      - title: Mehr
        url: /05_mehr.html

  - title: Architektur GDI
    url: /frontend.html
    children:
      - title: Client
        url: /frontend.html
      - title: Server
        url: /backend.html
      - title: APIs and Interfaces
        url: /api_and_interfaces.html
      - title: Libraries and Technologies
        url: /libraries_and_technologies.html

  - title: Getting Started
    url: /getting_started.html
