gittheme: minima
title: SkiScope
baseurl: "/SkiScope"

navbar:
  - title: Home
    url: /

  - title: Features
    url: /features.html
    children:
      - title: Suche
        url: /features.html#suche
      - title: Skigebiet Informationen
        url: /features.html#skigebiet-informationen
      - title: Wetterdaten
        url: /features.html#wetterdaten
      - title: Layersteuerung
        url: /features.html#layersteuerung
      - title: Shortcut maximale Schneehöhe
        url: /features.html#shortcut_maximale_schneehoehe
      - title: Nice to know
        url: /features.html#nice_to_know

  - title: Architektur GDI
    url: /architektur_gdi.html
    children:
      - title: Client
        url: /architektur_gdi.html#client
      - title: Server
        url: /architektur_gdi.html#server
      - title: APIs and Interfaces
        url: /architektur_gdi.html#api_and_interfaces
      - title: Libraries and Technologies
        url: /architektur_gdi.html#libraries_and_technologies

  - title: Getting Started
    url: /getting_started.html
