gittheme: minima
title: SkiScope
baseurl: "/SkiScope"

navbar:
  - title: Home
    url: /

  - title: Features
    url: /features.html
    children:
      - title: Suche
        url: /features.html#suche
      - title: Skigebiet Informationen
        url: /features.html#skigebiet-informationen
      - title: Wetterdaten
        url: /features.html#wetterdaten
      - title: Layersteuerung
        url: /features.html#layersteuerung
      - title: Shortcut maximale Schneehöhe
        url: /features.html#shortcut_maximale_schneehöhe
      - title: Mehr
        url: /features.html#mehr

  - title: Architektur GDI
    url: /frontend.html
    children:
      - title: Client
        url: /frontend.html#client
      - title: Server
        url: /backend.html#server
      - title: APIs and Interfaces
        url: /api_and_interfaces.html#api_and_interfaces
      - title: Libraries and Technologies
        url: /libraries_and_technologies.html#libraries_and_technologies

  - title: Getting Started
    url: /getting_started.html
